# Generated by Django 2.2 on 2020-05-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200516_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderanswersubmite',
            name='answer',
        ),
        migrations.AddField(
            model_name='orderanswersubmite',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Answer'),
        ),
    ]
