# Generated by Django 2.2 on 2020-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200518_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderanswersubmite',
            name='answer',
        ),
        migrations.AddField(
            model_name='orderanswersubmite',
            name='answer',
            field=models.ManyToManyField(to='core.Answer'),
        ),
    ]
