# Generated by Django 2.2 on 2020-05-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200518_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='answer', to='core.Answer'),
        ),
    ]
