# Generated by Django 3.0.5 on 2020-05-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_answer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuetionQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='ref_code',
        ),
    ]
