# Generated by Django 3.0.5 on 2020-05-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200507_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='quetionquantity',
            name='quetion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
    ]
