# Generated by Django 2.2 on 2020-05-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_voteorder_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerquantity',
            name='user',
        ),
        migrations.AlterField(
            model_name='answerquantity',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.Answer'),
        ),
    ]
