# Generated by Django 3.0.5 on 2020-05-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200507_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='request_quantity',
        ),
        migrations.RemoveField(
            model_name='quetionquantity',
            name='ref_code',
        ),
        migrations.AddField(
            model_name='question',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quetionquantity',
            name='request_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
