# Generated by Django 3.0.5 on 2020-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200507_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='request_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='question_req',
            field=models.ManyToManyField(to='core.Question'),
        ),
        migrations.DeleteModel(
            name='QuetionQuantity',
        ),
    ]
