# Generated by Django 2.2 on 2020-05-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_answerquantity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerquantity',
            name='user',
        ),
    ]
