# Generated by Django 3.0.5 on 2020-05-07 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200507_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='request_quantity',
        ),
        migrations.CreateModel(
            name='QuetionQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_quantity', models.PositiveIntegerField(default=0)),
                ('quetion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
