# Generated by Django 2.2 on 2020-05-26 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_answerquantity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='voteorder',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='voteorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voteorder',
            name='vote_request',
        ),
        migrations.DeleteModel(
            name='AnswerQuantity',
        ),
        migrations.DeleteModel(
            name='VoteOrder',
        ),
    ]
