# Generated by Django 3.0.5 on 2020-05-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200508_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quetionquantity',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
