# Generated by Django 3.0.5 on 2020-05-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200508_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='request_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='QuetionQuantity',
        ),
    ]
