# Generated by Django 2.2 on 2020-05-26 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200527_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecounter',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Like'),
        ),
    ]
