# Generated by Django 2.2 on 2020-05-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_likecounter_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecounter',
            name='like',
        ),
    ]
