# Generated by Django 3.0.5 on 2020-05-08 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200508_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='request_quantity',
        ),
        migrations.CreateModel(
            name='QuestionQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_quantity', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='question_req',
            field=models.ManyToManyField(to='core.QuestionQuantity'),
        ),
    ]
