# Generated by Django 2.2 on 2020-05-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200527_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislikes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_answer', to='core.Dislike'),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_answer', to='core.Like'),
        ),
    ]
