# Generated by Django 2.2 on 2020-07-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_question_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AlterField(
            model_name='daneshjoo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='user',
            field=models.ManyToManyField(to='core.User'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(to='core.User'),
        ),
        migrations.AlterField(
            model_name='orderanswersubmite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AlterField(
            model_name='orderquestionquantity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AlterField(
            model_name='questionquantity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
