# Generated by Django 3.0.5 on 2020-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ref_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
