# Generated by Django 2.2 on 2020-05-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200509_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
