# Generated by Django 2.2 on 2020-05-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200510_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
