# Generated by Django 2.2 on 2020-05-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200510_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(related_name='answer', to='core.Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question', to='core.Question'),
        ),
    ]
