# Generated by Django 2.2 on 2020-05-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200511_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(to='core.Answer'),
        ),
    ]
