# Generated by Django 2.2 on 2020-05-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200511_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderanswersubmite',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
