# Generated by Django 2.2 on 2020-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200511_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='answer', to='core.Answer'),
        ),
    ]
