# Generated by Django 2.2 on 2020-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200512_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteorder',
            name='vote_request',
            field=models.ManyToManyField(to='core.AnswerQuantity'),
        ),
    ]
