# Generated by Django 2.2 on 2020-05-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200512_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='poity',
            new_name='point',
        ),
    ]
