# Generated by Django 2.2 on 2020-05-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200514_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='zaman_tahvil',
        ),
    ]
