# Generated by Django 2.2 on 2020-05-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200515_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderanswersubmite',
            name='answer',
            field=models.ManyToManyField(to='core.Answer'),
        ),
    ]
