# Generated by Django 2.2 on 2020-05-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200515_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='answer', to='core.Answer'),
        ),
        migrations.DeleteModel(
            name='OrderAnswerSubmite',
        ),
    ]
