# Generated by Django 2.2 on 2020-05-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20200515_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderanswersubmite',
            name='answer',
        ),
        migrations.AddField(
            model_name='orderanswersubmite',
            name='question',
            field=models.ManyToManyField(to='core.Question'),
        ),
    ]
