# Generated by Django 2.2 on 2020-05-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20200515_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='username',
            new_name='user',
        ),
    ]
