# Generated by Django 2.2 on 2020-05-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200515_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderanswersubmite',
            name='question',
            field=models.ManyToManyField(to='core.Answer'),
        ),
    ]
