# Generated by Django 2.2 on 2020-05-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20200515_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderanswersubmite',
            old_name='question',
            new_name='answer',
        ),
    ]
