# Generated by Django 2.2 on 2020-05-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20200515_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderanswersubmite',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OrderAnswerSubmite'),
        ),
    ]
