# Generated by Django 2.2 on 2020-05-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200515_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='order',
        ),
        migrations.AddField(
            model_name='orderanswersubmite',
            name='answer',
            field=models.ManyToManyField(to='core.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='answer', to='core.Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='core.Question'),
        ),
    ]
