# Generated by Django 2.2 on 2020-05-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20200515_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderanswersubmite',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
    ]
