# Generated by Django 2.2 on 2020-07-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_new_v', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ref_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
