# Generated by Django 2.2 on 2020-07-20 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_new_v', '0004_auto_20200718_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_of_request',
            field=models.ManyToManyField(blank=True, related_name='reuqested', to=settings.AUTH_USER_MODEL),
        ),
    ]
